### ISSUE TITLE
verilator is used by default

### ISSUE THREAD

**Issue by mattvenn** [vbrange/wrapped_qarma#3]
think I opened an issue about this before?

**Comment by mattvenn** [comment]
![image](https://user-images.githubusercontent.com/634220/122018317-08823580-cdc3-11eb-9cfb-6c06bf6cdde1.png)

maybe you need to tighten your version check? I have verilator 4 but it doesn't work with the --build flag

**Comment by vbrange** [comment]
Got rid of the verilator
